version: '3.9'

services:
  server:
    build:
      context: ./back-end
      dockerfile: ./Dockerfile.dev
    environment:
      - PORT=5000
    ports:
      - "5000:5000"

  client:
    build:
      context: ./front-end
      dockerfile: ./Dockerfile.dev
    environment:
      - REACT_APP_PORT=5000
    ports:
      - "3000:3000"
    depends_on:
      - server

